# Base Formatting Rules
max_width = 100   # Maximum line width (default: 100)
hard_tabs = false
tab_spaces = 4    # Indentation with 4 spaces
edition = "2024"  # Rust edition (align with Cargo.toml)

# Function and Expression Formatting
fn_params_layout = "Vertical" # Align function arguments vertically
chain_width = 80              # Chain call width threshold

# Import Organization
reorder_imports = true # Alphabetically sort imports

# Miscellaneous
merge_derives = false           # Keeps each #[derive] attribute on a separate line
use_field_init_shorthand = true # Use shorthand field initialization syntax
